Gene/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('lead_mgt.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

lead_mgt/urls.py
from django.urls import path

from . import views

app_name = 'lead_mgt'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_lead/', views.add_lead, name='add_lead'),
    path('affiliate/', views.affiliate_dashboard, name='affiliate_dashboard'),
    path('download_leads/', views.add_lead, name='add_lead'),
    path('call_dashboard/', views.call_dashboard, name='call_dashboard'),
    path('call_import/<batch_number>/', views.call_import, name='call_import'),
    path('import/', views.import_call, name='import_call'),
    path('import_status/<batch_number>/', views.import_status, name='import_status'),
    path('landing/', views.landing, name='landing'),
    path('leads/', views.agent_view_lead, name='agent_view_lead'),
    path('lead_detail/<lead_id>/', views.call_lead_detail, name='call_lead_detail'),
    path('refer/<ref>/', views.referred, name='referred'),
    path('redeem/', views.redeem_points, name='redeem_points'),
    path('redeem/<option>/', views.redeem, name='redeem'),
    path('supervisor/', views.supervisor_dashboard, name='supervisor_dashboard'),
    path('supervisor_leads/', views.supervisor_leads, name='supervisor_leads'),
    path('confirm_import/<batch_number>/', views.confirm_import, name='confirm_import'),
    path('signup/', views.signup, name='signup'),
    path('update_vehicle/', views.update_vehicle, name='update_vehicle'),
    path('profile/', views.affiliate_profile, name='profile'),

]

lead_mgt/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Lead(models.Model):
    agent = models.ForeignKey(User, null=True, on_delete=models.SET_DEFAULT, default=1)
    lead_date = models.DateField(verbose_name='Date')
    title = models.CharField(max_length=10, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    status = models.CharField(max_length=30,
                              default='submitted',
                              choices=(
                                  ('submitted', 'submitted'),
                                  ('unreachable', 'unreachable'),
                                  ('unreachable_follow_up', 'unreachable follow up'),
                                  ('wrong_number', 'wrong number'),
                                  ('converted', 'converted'),
                                  ('not_interested', 'not interested'),
                                  ('not_expired', 'not expired'),
                                  ('call_later', 'call later'),
                                  ('quoted', 'quoted'),
                                  ('bad_line', 'bad line')
                              )
                              )
    next_call_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Call(models.Model):
    call_agent = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    call_date = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True)
    type = models.CharField(max_length=20, blank=True)
    open_status = models.CharField(max_length=30, blank=True)
    close_status = models.CharField(max_length=30,
                                    blank=True,
                                    choices=(
                                        ('unreachable', 'unreachable'),
                                        ('unreachable_follow_up', 'unreachable follow up'),
                                        ('wrong_number', 'wrong number'),
                                        ('converted', 'converted'),
                                        ('not_interested', 'not interested'),
                                        ('not_expired', 'not expired'),
                                        ('call_later', 'call later'),
                                        ('quoted', 'quoted'),
                                        ('bad_line', 'bad line')
                                    )
                                    )

    def __str__(self):
        return self.lead.last_name


class CommissionPayment(models.Model):
    payment_date = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    paid_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    recipient = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='recipient')

    def __str__(self):
        '{} - {}'.format(self.recipient.username, self.amount)


class Earning(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    earning_date = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    paid = models.BooleanField(default=False)


class Vehicle(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    make = models.CharField(max_length=50, blank=True)
    vehicle_model = models.CharField(max_length=50, blank=True)
    reg_number = models.CharField(max_length=20, blank=True)
    insurance_expiry = models.DateField(null=True)
    status = models.CharField(max_length=20,
                              default='open',
                              blank=True,
                              choices=(
                                       ('open', 'open'),
                                       ('closed', 'closed')
                              )
                              )
    policy_type = models.CharField(max_length=20,
                                   blank=True,
                                   choices=(
                                       ('ftp', 'third party'),
                                       ('comp', 'comprehensive')
                                   )
                                   )
    policy_number = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return '{} {}({})'.format(self.make, self.vehicle_model, self.reg_number)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ref = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='referer')
    ref_code = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=50)
    birth_date = models.DateField(blank=True, null=True)
    city = models.CharField(max_length=50)
    bank = models.CharField(max_length=50, blank=True)
    account_number = models.CharField(max_length=50, blank=True)
    ecocash_name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        if self.ref:
            return '{} < {}'.format(self.user.username, self.ref.username)
        else:
            return self.user.username

    def affiliate_1_count(self):
        return self.user.referer.all().count()

    def affiliate_2_count(self):
        count = 0
        for affiliate in self.user.referer.all():
            count += affiliate.affiliate_1_count()

        return count

    def affiliate_3_count(self):
        count = 0
        for affiliate in self.user.referer.all():
            count += affiliate.affiliate_2_count()
        return count

    def affiliate_1_2_count(self):
        return self.affiliate_1_count() + self.affiliate_2_count()

    def affiliate_total_count(self):
        return self.affiliate_1_count() + self.affiliate_2_count() + self.affiliate_3_count()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Interaction(models.Model):
    batch_number = models.IntegerField()
    lead = models.CharField(max_length=10)
    interaction_date = models.DateField()
    user = models.CharField(max_length=10)
    notes = models.TextField(blank=True)
    result = models.CharField(max_length=50)
    database_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.result


class RawCallData(models.Model):
    batch_number = models.IntegerField()
    database_date = models.DateTimeField(auto_now_add=True)
    lead_id = models.CharField(max_length=20)
    lead_date = models.CharField(max_length=20)
    lead_name = models.CharField(max_length=160)
    lead_phone = models.CharField(max_length=50)
    current_status = models.CharField(max_length=50)
    current_next_call = models.CharField(max_length=50, blank=True, null=True)
    agent_id = models.CharField(max_length=50, blank=True)
    call_date = models.CharField(max_length=20, blank=True)
    disposition = models.CharField(max_length=50)
    notes = models.CharField(max_length=160, blank=True, null=True)
    new_next_call = models.CharField(max_length=20, blank=True, null=True)
    policy_number = models.CharField(max_length=50, blank=True, null=True)
    policy_type = models.CharField(max_length=20,
                                   blank=True,
                                   choices= (
                                       ('ftp', 'full third party'),
                                       ('comp', 'comprehensive')
                                   )
                                   )
    upload_status = models.CharField(max_length=20,
                                     blank=True,
                                     choices=(
                                         ('success', 'success'),
                                         ('failed', 'failed')
                                     )
                                     )

    def __str__(self):
        return "{} > {}".format(self.agent_id, self.lead_name)


class ImportErrors(models.Model):
    call = models.ForeignKey(RawCallData, on_delete=models.CASCADE)
    error_text = models.CharField(max_length=120)


class PointSchedule(models.Model):
    scheme_name = models.CharField(max_length=20)
    level_0_comp = models.IntegerField()
    level_1_comp = models.IntegerField()
    level_2_comp = models.IntegerField()
    level_3_comp = models.IntegerField()
    level_0_ftp = models.IntegerField()
    level_1_ftp = models.IntegerField()
    level_2_ftp = models.IntegerField()
    level_3_ftp = models.IntegerField()

    def __str__(self):
        return self.scheme_name


class PointsEarned(models.Model):
    points_date = models.DateTimeField(auto_now_add=True)
    affiliate = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    points = models.IntegerField()
    type = models.CharField(max_length=20)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.affiliate.username, self.points)


class RedemptionSchedule(models.Model):
    points = models.IntegerField()
    amount = models.IntegerField()

    def __str__(self):
        return '{}-{}'.format(self.points, self.amount)


class Redemption(models.Model):
    affiliate = models.ForeignKey(User, on_delete=models.CASCADE)
    points = models.IntegerField()
    amount = models.IntegerField()

lead_mgt/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory

from .models import Call, Lead, Profile, Vehicle


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        exclude = ['agent', 'status', 'next_call_date']

    def __init__(self, *args, **kwargs):
        super(LeadForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control input-sm'


class VehileForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        exclude = ['lead']


class UploadFileForm(forms.Form):
    file = forms.FileField()


VehicleFormset = inlineformset_factory(
    Lead,
    Vehicle,
    fields=(
        'make',
        'vehicle_model',
        'reg_number',
        'insurance_expiry',
    ),
    extra=1,
    can_delete=False
)


VehicleFormset1 = inlineformset_factory(
    Lead,
    Vehicle,
    fields=(
        'id',
        'make',
        'vehicle_model',
        'reg_number',
        'insurance_expiry',
        'status',
        'policy_type',
        'policy_number'
    ),
    extra=1,
    can_delete=False
)


class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = ['close_status', 'notes']


class AffiliateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birth_date', 'city', 'account_number', 'ecocash_name',]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

lead_mgt/templates/lead_mgt/add_lead.html
{% extends 'lead_mgt/index-3.html' %}

{% block content %}

    <form action="{% url 'lead_mgt:add_lead' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-example-wrap mg-t-30">
                    <div class="cmp-tb-hd cmp-int-hd">
                        <h2>New lead</h2>
                    </div>
                    {% if lead_form.non_field_errors %}
                        {{ lead_form.non_field_errors }}
                    {% endif %}

                    {% for hiddem_field in lead_form.hidden_fields %}
                        {{ hiddem_field.errors }}
                        {{ hiddem_field }}
                    {% endfor %}

                    {% for field in lead_form.visible_fields %}
                        <div class="form-example-int form-horizental">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                        <label class="hrzn-fm">{{ field.label_tag }}</label>
                                    </div>
                                    <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                        {% if field.errors %}
                                            {{ field.errors }}
                                        {% endif %}
                                        <div class="nk-int-st">
                                            {{ field }}
                                        </div>
                                        {{ field.help_text }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-example-int form-horizental">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm">{{ field.label_tag }}</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    {% if field.errors %}
                                        {{ field.errors }}
                                    {% endif %}
                                    <div class="nk-int-st">
                                        {{ field }}
                                    </div>
                                    {{ field.help_text }}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


                {{ vehicle_formset.management_form }}

                {% for form in vehicle_formset %}
                    <div id="{{ form.prefix }}-row" class="dynamic-form form-example-wrap mg-t-30">
                        <div class="cmp-tb-hd cmp-int-hd">
                            <h4>Vehicle</h4>
                        </div>
                        <div class="form-example-int form-horizental mg-t-15">
                            <div class="row field_cont">

                                {% for field in form.visible_fields %}

                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                        <div class="nk-int-mk">
                                            <h2>{{ field.label_tag }}</h2>
                                        </div>
                                        <div class="form-group ic-cmp-int ">
                                            <div class="form-ic-cmp">
                                                <i class="notika-icon notika-draft"></i>
                                            </div>
                                            <div class="nk-int-st form_ctrl">
                                                <!--input type="text" class="form-control"-->
                                                {{ field }}
                                                <!--label class="nk-label">{{ field.label_tag }}</label-->
                                            </div>
                                        </div>
                                    </div>

                                {% endfor %}

                                    <!--div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                        <div class="nk-int-mk">
                                            <h2>{{ field.label_tag }}</h2>
                                        </div>
                                        <div class="form-group ic-cmp-int ">
                                            <div class="form-ic-cmp">
                                                <i class="notika-icon notika-draft"></i>
                                            </div>
                                            <div class="nk-int-st form_ctrl">
                                                <!--input type="text" class="form-control"--
                                                {{ field }}
                                                <!--label class="nk-label">{{ field.label_tag }}</label--
                                            </div>
                                        </div>
                                    </div-->




                            </div>

                        <!--a id="remove-{{ form.prefix }}-row" href="javascript:void(0)" class="delete-row">Delete</a-->

                        </div>
                    </div>
                {% endfor %}

                <div class="form-example-int mg-t-15">
                    <a href="javascript:void(0)" class="add-row btn btn-primary notika-btn-primary waves-effect">Add vehicle</a>
                    <button class="btn btn-success notika-btn-success">Submit</button>
                </div>

            </div>
        </div>

    </form>



{% endblock %}

{% block script %}
     <script type="text/javascript">

        $(function () {
            $('.add-row').click(function() {
                return addForm(this, 'vehicle_set');
            });
            $('.delete-row').click(function() {
                return deleteForm(this, 'vehicle_set');
            })
        });

        $(document).ready(function () {
            $('.form_ctrl > input').addClass('form-control');
        })
    </script>
{% endblock %}

lead_mgt/templates/lead_mgt/agent_view_leads.html
{% extends 'lead_mgt/index-3.html' %}

{% block content %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>My leads</h2>
										<p>Leads submited will appear below</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-3">
								<div class="breadcomb-report">
									<button data-toggle="tooltip" data-placement="left" title="Download Report" class="btn"><i class="notika-icon notika-sent"></i></button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomfb area End-->


    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="basic-tb-hd">
                            <h2>Leads</h2>
                            <p>You can sort the records by clicking any of the column headings.  Click a name to see more detail</p>
                        </div>
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped hover">
                                <thead>
                                    <tr>
                                        <th>Date </th>
                                        <th>Name</th>
                                        <th class="dt-head-center">Status</th>
                                        <th class="dt-head-center">Earned</th>
                                        <th class="dt-head-center">Payout status</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for lead in leads %}
                                    <tr>
                                        <td>{{ lead.lead_date }}</td>
                                        <td>{{ lead.title }} {{ lead.first_name }} {{ last_name }}</td>
                                        <td class="dt-body-center">Awaiting call</td>
                                        <td class="dt-body-center">0.00</td>
                                        <td class="dt-body-center">Pending</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Date </th>
                                        <th>Name</th>
                                        <th class="dt-head-center">Status</th>
                                        <th class="dt-head-center">Earned</th>
                                        <th class="dt-head-center">Payout status</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

lead_mgt/templates/lead_mgt/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'lead_mgt/style.css' %}">
    <title>Title</title>
</head>
<body>
    hope this works
</body>
</html>

lead_mgt/templates/lead_mgt/supervisor_leads.html
{% extends 'lead_mgt/index-3.html' %}

{% load widget_tweaks %}

{% block content %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Available leads</h2>
										<p>Leads awaiting contact</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-3">
								<div class="breadcomb-report">
									<button data-toggle="tooltip" data-placement="left" title="Download Report" class="btn"><i class="notika-icon notika-sent"></i></button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomfb area End-->

    <div class="datepicker-area margin-40-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="datepicker-int mg-t-30">
                        <div class="cmp-tb-hd">
                            <h4>Filter leads</h4>
                            <p>Filter leads to narrow selection</p>
                        </div>
                        <form method="get">
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <div class="form-group nk-datapk-ctm form-elet-mg" id="data_1">
                                        <label>{{ filter.form.lead_date.label_tag  }}</label>
                                        <div class="input-group date nk-int-st">
                                            <span class="input-group-addon"></span>
                                            {% render_field filter.form.lead_date class="form-control" autocomplete="off" %}
                                            <!--input type="text" class="form-control" value="03/19/2018"-->
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <div class="nk-int-mk sl-dp-mn sm-res-mg-t-10">
                                        <h2>{{ filter.form.status.label_tag  }}</h2>
                                    </div>
                                    <div class="bootstrap-select fm-cmp-mg">

                                        {% render_field filter.form.status class="selectpicker" data-live-search="true" autocomplete="off" %}
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <div class="form-group nk-datapk-ctm form-elet-mg" id="data_1">
                                        <label>{{ filter.form.next_call_date.label_tag  }}</label>
                                        <div class="input-group date nk-int-st">
                                            <span class="input-group-addon"></span>
                                            {% render_field filter.form.next_call_date class="form-control" autocomplete="off" %}
                                            <!--input type="text" class="form-control" value="03/19/2018"-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15 ">
                                <input class="btn btn-success notika-btn-success waves-effect mg-t-20 std-background" type="submit" value="Filter" name="filter">
                                <a href="{% url 'lead_mgt:supervisor_leads' %}" class="btn btn-success notika-btn-success waves-effect mg-t-20 std-background">Clear filters</a>
                                <input class="btn btn-success notika-btn-success waves-effect mg-t-20 secondary-background" type="submit" value="Download" name="download">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="basic-tb-hd">
                            <h2>Leads</h2>
                        </div>
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped hover">
                                <thead>
                                    <tr>
                                        <th>ID </th>
                                        <th class="dt-head-center">Date</th>
                                        <th>Name</th>
                                        <th class="dt-head-center">Phone</th>
                                        <th class="dt-head-center">Status</th>
                                        <th class="dt-head-center">Next call date</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for lead in filter.qs %}
                                    <tr>
                                        <td>{{ lead.id }}</td>
                                        <td>{{ lead.lead_date }}</td>
                                        <td>{{ lead.title }} {{ lead.first_name }} {{ last_name }}</td>
                                        <td class="dt-body-center">{{ lead.phone_number }}</td>
                                        <td class="dt-body-center">{{ lead.status }}</td>
                                        <td class="dt-body-center">{{ lead.next_call_date }}</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                     <tr>
                                        <th>ID </th>
                                        <th class="dt-head-center">Date</th>
                                        <th>Name</th>
                                        <th class="dt-head-center">Phone</th>
                                        <th class="dt-head-center">Status</th>
                                        <th class="dt-head-center">Next call date</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block script %}
    <script>
    function downloadReport() {
        $.ajax({
            url: '/download_leads/',
            method: 'POST',
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                lead_date: $('#id_lead_date').val(),
                status: $('#id_status').val(),
                next_call_date: $('#id_next_call_date').val()
            },
            success: function (data) {
                console.log('Did itt!!')
            }

        })
        
    }

    $(document).ready(function () {
        $('form > input').onchange(function () {
            $('input[name="download"]').disable()
        })
    })
    </script>

{% endblock %}